### ISSUE TITLE
BubbleMenu buttons are too small on small screens

### ISSUE THREAD

**Issue by kflis** [uci-sdcl/CaliSmall#28]
Tested on my Galaxy Nexus.

**Comment by kflis** [comment]
![2013-05-09 00 15 13](https://f.cloud.github.com/assets/3364624/481854/7629d0ac-b878-11e2-9928-7f6002606639.png)

**Comment by nfmangano** [comment]
Rotate that frown upside down.

**Comment by kflis** [comment]
I tried and missed the rotate button!

**Comment by micheleb** [comment]
I have a fix ready, will commit later in the (Italian) day

**Comment by nfmangano** [comment]
Get a bigger phone!

https://discussions.apple.com/___sbsstatic___/migration-images/131/13153261-1.jpg

**Comment by kflis** [comment]
Oh and I forgot to mention, the selection circle seems too small, too! 
![2013-05-09 00 28 47](https://f.cloud.github.com/assets/3364624/481880/377141c2-b87a-11e2-8aca-312d8080f952.png)

**Comment by micheleb** [comment]
yup, the fix makes all of that screen size independent

**Comment by kflis** [comment]
Great!
